### PR TITLE
Remove Mechanism-2 (#372), Add a 3-fold on-demand Reload button, Fix extra minor bugs

### LINKED ISSUE #493: Feature: Expose more easily last the two versions of a saved exercise
**Related issue(s) or PR(s):** N/A

**Related project scope(s):** UI, learn-ocaml-client, Teacher-dashboard

**Related user(s):** @erikmd 

## The problem

Currently, the webapp views (student UI vs. teacher dashboard) only show one flavor of the "last version of the exercise":

* the last contents of save.json/`exercises-editors` for the student UI
* the last version of the graded exercise for the teacher dashboard

Additionally it is feasible for student to also retrieve the last version of the graded exercises by clicking on `Download all source files` in the home page. But it is certainly not very user-friendly.

### Wanted solution

* In the student UI:
  * Replace the `Reset` button and icon with a drop-down button that proposes:
    * `Reset to template`
    * `Reset to last graded version`
    * `Reset to last saved draft`
* In the teacher dashboard:
  * Add another tab `Draft` after `Answer` that displays the last saved draft (although it is not taken into account for the grading; maybe add a tooltip in the Draft tab to remind this)
* In learn-ocaml-client:
  * Double-check what `learn-ocaml-client fetch` fetches
  * Provide a similar command, e.g., `learn-ocaml-client fetch-graded`, to fetch the last graded version

Remarks to be aware when reviewing this feature:
* Check that in the student UI, when resetting the editor with one of the 3 choices, the exercise is not automatically synced yet.
* Check what happens w.r.t. the refresh of the teacher dashboard when an exercise has been very recently synced/graded → open a new issue if need be.
* TODO internationalization with @erikmd

### Considered alternatives

N/A

## Additional context

N/A

### LINKED ISSUE #505: Bug: Mechanism-2 of PR #372 does not work
**Related issue(s) or PR(s):**
- #372

**Related project scope(s):** Web UI

**Related user(s):**
- @erikmd
- @yurug

## Bug description

The test triggering the dialog "A more recent answer exists on the server. Do you want to fetch the new version?" has false negatives and false positives.
Moreover, a click on "Fetch from server & overwrite" does not trigger a fetch from the backend.

### To reproduce

1. Run a local instance of Learn-OCaml (where the timing 180s is replaced with 10s)
1. Browse http://localhost:8080 and open the same exercise in two different browsers
1. (in both Browsers) the Sync button should be grayed at first ("bug 0")
1. (in Browser 1) change the text then sync, wait for 10s
1. (in Browser 2) edit text → nothing happens (bug 1: false negative)
1. (in Browser 1) edit text → the dialog shows up (bug 2: false positive), click on Ignore
1. (in Browser 2) click on sync, wait for 10s
1. ((in Browser 1) click on sync, wait for 10s) (optional)
1. (in Browser 2) edit text → the dialog shows up
1. (in Browser 2) click on Fetch from server & overwrite → same code of Browser 2 (bug 3: no fetch)

### Expected behavior

* Fix the three bugs above and/or disable the timer logic and the automatic check.
* Make it possible to do a **fetch** on demand (without waiting for 180s), along with #493.

## Current configuration

* OS name (and version): GNU/Linux
* Browser name (and version): Firefox and Chromium
* `learn-ocaml --version`: 0.14.0
* `git describe --long --always --abbrev=40 --tags`: v0.14.0-14-g9bc28a63ab13986dab36c9843142094b05ab5856

## Additional context

The 1st and 3rd bug crept into master despite the testing of #372 certainly because this testing only involved two tabs of the *same* browser (with a common local storage…)

### PR DESCRIPTION
**Pull request by erikmd**
* **Kind:** bugfix

* Close #505
* Close #493

### Description

Replace "Mechanism 2" (from PR 372) with a more expressive set of reload features, and fixes minor bugs along the way.

### Checklist

* [x] Read the [CONTRIBUTING.md](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md) guide and:
  * [x] Use [Atomic Commits](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#atomic-commits) so each commit gathers a single logical change
  * [x] Use [Conventional Commits](https://github.com/ocaml-sf/learn-ocaml/blob/master/CONTRIBUTING.md#conventional-commits) regarding commit messages (needed by our release toolchain)
  

### Note to maintainers

* Read [this wiki page](https://github.com/ocaml-sf/learn-ocaml/wiki/Checklist-for-testing-and-merging-a-PR)
* Make sure the PR has a milestone
* Assign yourself before merging
* This PR should be merged as is, **NOT SQUASHED**

### CODE REVIEW

**Comment by erikmd** [comment]
Hi @yurug, as promised I finished working on this PR that fully fixes #505, plus 2 related minor bugs.

In dynamic deployment mode, we now get a 3-fold button like this:

## English
2022-12-29_01-40-38_Screenshot_english

## French
2022-12-29_01-40-59_Screenshot_french

## Remarks

* To test the PR, feel free to download the static binaries that are automatically put as PR checks & commit statuses   :heavy_check_mark: → **learn-ocaml-linux-x86_64.tar.gz (artifact)** & **learn-ocaml-www.zip (artifact)** (see [PR #504 doc](https://github.com/ocaml-sf/learn-ocaml/blob/504299a160b850071f927533a4b24795a5e7a8a6/docs/howto-deploy-learn-ocaml-statically.md))
* @yurug If your extra tests are OK as well, please don't squash this PR (a **regular merge** will be required here)

**Comment by yurug** [comment]
@erikmd I have tested the feature and found an issue. When there are no versions on the server, retrieving the latest graded version (or the last synchronized version) does not work: the dialog box is opened but clicking on "OK" does nothing. (The dialog box stays displayed.)

The test has been performed on Google Chrome.

**Comment by erikmd** [comment]
@yurug thanks for your review!

I've just pushed after our pair-programming rework/test, so feel free to merge (*not squash*) once the CI is green anew.

Thanks 👍

**Comment by erikmd** [comment]
Sorry @yurug, I've just noticed I had amended the last commit instead of the last-but-one. I'm doing this right now! stay tuned.

**Comment by erikmd** [comment]
> Sorry @yurug, I've just noticed I had amended the last commit instead of the last-but-one. I'm doing this right now! stay tuned.

Done → as one can see, my last force-push induces an [empty diff](https://github.com/ocaml-sf/learn-ocaml/compare/9b58cf29619b49be16d72b77271060cbdb2e6eba..dd69f3c9b0995817f789d9f77ada6cd84ca40075)

**Comment by erikmd** [comment]
Hi again @yurug!,

> … once the CI is green anew.

this is now the case 🙃👍

**Pull request merged**
