### PR TITLE
Create an learn-ocaml-client.opam file.

### PR DESCRIPTION
**Pull request by yurug**

### CODE REVIEW

**Comment by yurug** [comment]
I guess I am done here. What do you think @erikmd ?

**Comment by erikmd** [comment]
that sounds great, thank you @yurug!

I thoroughly tested the PR (pinning+building learn-ocaml-client only, from scratch (using a clean switch) and using it from `learn-ocaml.el` which worked fine, then pinning+building learn-ocaml) and I noticed the following items:

1. I got an error because I had an old generated file `static/dune` that was untouched by learn-ocaml-client:

<details>

```
$ git describe --all --long --abbrev=40 --always --dirty
heads/pr/342-0-g809b6539b208340ae9570a3e50643fc6ead6712c

$ opam switch create . ocaml-base-compiler.4.05.0 --no-install

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ocaml-base-compiler.4.05.0] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-bigarray.base
∗ installed base-threads.base
∗ installed base-unix.base
∗ installed ocaml-base-compiler.4.05.0
∗ installed ocaml-config.1
∗ installed ocaml.4.05.0
Done.
# Run eval $(opam env) to update the current shell environment

$ eval $(opam env)

$ opam pin add -n -y -k path learn-ocaml-client .
Package learn-ocaml-client does not exist, create as a NEW package? [Y/n] y
[learn-ocaml-client.~dev] synchronised from file://$HOME/forge/git/learn-ocaml
learn-ocaml-client is now pinned to file://$HOME/forge/git/learn-ocaml (version 0.11)

$ opam install learn-ocaml-client

<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[learn-ocaml-client.0.11] no changes from file://$HOME/forge/git/learn-ocaml

The following actions will be performed:
  ∗ install conf-m4                 1            [required by ocamlfind]
  ∗ install ocamlbuild              0.14.0       [required by omd]
  ∗ install cmdliner                1.0.4        [required by learn-ocaml-client]
  ∗ install base-num                base         [required by num]
  ∗ install conf-pkg-config         1.1          [required by conf-libssl]
  ∗ install conf-which              1            [required by ssl]
  ∗ install dune                    1.6.3        [required by learn-ocaml-client]
  ∗ install ocamlfind               1.8.1        [required by learn-ocaml-client]
  ∗ install uchar                   0.0.2        [required by jsonm]
  ∗ install num                     0            [required by sexplib]
  ∗ install conf-libssl             1            [required by ssl]
  ∗ install stdlib-shims            0.1.0        [required by fmt]
  ∗ install seq                     0.2.2        [required by re]
  ∗ install result                  1.4          [required by ocaml-migrate-parsetree, lwt]
  ∗ install ppx_derivers            1.2.1        [required by ocaml-migrate-parsetree, ppx_type_conv]
  ∗ install magic-mime              1.1.2        [required by cohttp-lwt-unix]
  ∗ install jbuilder                transition   [required by base]
  ∗ install cppo                    1.6.6        [required by asak]
  ∗ install bigarray-compat         1.0.0        [required by eqaf, hex]
  ∗ install topkg                   1.0.1        [required by jsonm]
  ∗ install ppx_tools               5.0+4.05.0   [required by learn-ocaml-client]
  ∗ install pprint                  20180528     [required by ocp-ocamlres]
  ∗ install ocp-build               1.99.20-beta [required by ocp-indent-nlfork]
  ∗ install base-bytes              base         [required by digestif, base64, omd]
  ∗ install re                      1.9.0        [required by cohttp]
  ∗ install ocaml-migrate-parsetree 1.3.1        [required by ppx_fields_conv, fieldslib, ppx_sexp_conv]
  ∗ install sexplib                 v0.9.3       [required by cohttp, base, ezjsonm]
  ∗ install ppx_traverse_builtins   v0.9.0       [required by ppx_metaquot]
  ∗ install ocaml-compiler-libs     v0.9.0       [required by ppx_core]
  ∗ install asak                    0.2          [required by learn-ocaml-client]
  ∗ install cstruct                 5.1.1        [required by eqaf, hex]
  ∗ install uutf                    1.0.2        [required by jsonm]
  ∗ install fmt                     0.8.8        [required by cohttp-lwt-unix]
  ∗ install ocp-indent-nlfork       1.5.3        [required by learn-ocaml-client]
  ∗ install stringext               1.6.0        [required by cohttp]
  ∗ install ssl                     0.5.5        [required by lwt_ssl]
  ∗ install omd                     1.3.1        [required by learn-ocaml-client]
  ∗ install base64                  2.3.0        [required by learn-ocaml-client]
  ∗ install astring                 0.8.3        [required by ocp-ocamlres]
  ∗ install ppx_tools_versioned     5.2.2        [required by lwt]
  ∗ install base                    v0.9.4       [required by learn-ocaml-client]
  ∗ install ppx_ast                 v0.9.1       [required by ppx_core]
  ∗ install hex                     1.4.0        [required by ezjsonm]
  ∗ install eqaf                    0.5          [required by digestif]
  ∗ install jsonm                   1.0.1        [required by cohttp, ezjsonm]
  ∗ install ocp-ocamlres            0.4          [required by learn-ocaml-client]
  ∗ install lwt                     3.3.0        [required by learn-ocaml-client]
          For the PPX, please install package lwt_ppx
          For Lwt_log and Lwt_daemon, please install package lwt_log
  ∗ install stdio                   v0.9.1       [required by ppx_core]
  ∗ install digestif                0.7.1        [required by learn-ocaml-client]
  ∗ install ezjsonm                 1.1.0        [required by learn-ocaml-client]
  ∗ install lwt_ssl                 1.1.3        [required by learn-ocaml-client]
  ∗ install logs                    0.7.0        [required by cohttp-lwt-unix]
  ∗ install ppx_core                v0.9.3       [required by ppx_fields_conv, ppx_sexp_conv]
  ∗ install ppx_optcomp             v0.9.0       [required by ppx_driver]
  ∗ install ppx_driver              v0.9.2       [required by ppx_fields_conv, fieldslib, ppx_sexp_conv]
  ∗ install ppx_metaquot            v0.9.0       [required by ppx_fields_conv, ppx_sexp_conv]
  ∗ install fieldslib               v0.9.0       [required by cohttp]
  ∗ install ppx_type_conv           v0.9.1       [required by ppx_fields_conv, ppx_sexp_conv]
  ∗ install ppx_sexp_conv           v0.9.0       [required by cohttp]
  ∗ install ppx_fields_conv         v0.9.0       [required by cohttp]
  ∗ install uri                     1.9.7        [required by cohttp, ocplib-json-typed]
  ∗ install ipaddr                  2.9.0        [required by conduit-lwt-unix]
  ∗ install ocplib-json-typed       0.6          [required by learn-ocaml-client]
  ∗ install cohttp                  1.1.1        [required by learn-ocaml-client]
  ∗ install conduit                 1.3.0        [required by conduit-lwt]
  ∗ install cohttp-lwt              1.1.1        [required by cohttp-lwt-unix]
  ∗ install conduit-lwt             1.3.0        [required by conduit-lwt-unix]
  ∗ install conduit-lwt-unix        1.3.0        [required by cohttp-lwt-unix]
  ∗ install cohttp-lwt-unix         2.1.3        [required by learn-ocaml-client]
  ∗ install learn-ocaml-client      0.11*
===== ∗ 70 =====
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[astring.0.8.3] found in cache
[base.v0.9.4] found in cache
[base64.2.3.0] found in cache
[bigarray-compat.1.0.0] found in cache
[cmdliner.1.0.4] found in cache
[cohttp.1.1.1] found in cache
[cohttp-lwt.1.1.1] found in cache
[cohttp-lwt-unix.2.1.3] found in cache
[conduit.1.3.0] found in cache
[conduit-lwt.1.3.0] found in cache
[conduit-lwt-unix.1.3.0] found in cache
[cppo.1.6.6] found in cache
[cstruct.5.1.1] found in cache
[digestif.0.7.1] found in cache
[dune.1.6.3] found in cache
[eqaf.0.5] found in cache
[ezjsonm.1.1.0] found in cache
[fieldslib.v0.9.0] found in cache
[fmt.0.8.8] found in cache
[hex.1.4.0] found in cache
[ipaddr.2.9.0] found in cache
[jsonm.1.0.1] found in cache
[logs.0.7.0] found in cache
[lwt.3.3.0] found in cache
[lwt_ssl.1.1.3] found in cache
[magic-mime.1.1.2] found in cache
[ocaml-compiler-libs.v0.9.0] found in cache
[ocaml-migrate-parsetree.1.3.1] found in cache
[ocamlbuild.0.14.0] found in cache
[ocamlfind.1.8.1] found in cache
[ocp-build.1.99.20-beta] found in cache
[asak.0.2] downloaded from cache at https://opam.ocaml.org/cache
[ocp-indent-nlfork.1.5.3] found in cache
[ocp-ocamlres.0.4] found in cache
[ocplib-json-typed.0.6] found in cache
[omd.1.3.1] found in cache
[pprint.20180528] found in cache
[ppx_ast.v0.9.1] found in cache
[ppx_core.v0.9.3] found in cache
[ppx_derivers.1.2.1] found in cache
[ppx_driver.v0.9.2] found in cache
[ppx_fields_conv.v0.9.0] found in cache
[ppx_metaquot.v0.9.0] found in cache
[ppx_optcomp.v0.9.0] found in cache
[ppx_sexp_conv.v0.9.0] found in cache
[ppx_tools.5.0+4.05.0] found in cache
[ppx_tools_versioned.5.2.2] found in cache
[ppx_traverse_builtins.v0.9.0] found in cache
[ppx_type_conv.v0.9.1] found in cache
[re.1.9.0] found in cache
[result.1.4] found in cache
[sexplib.v0.9.3] found in cache
[stdio.v0.9.1] found in cache
[stdlib-shims.0.1.0] found in cache
[stringext.1.6.0] found in cache
[topkg.1.0.1] found in cache
[uchar.0.0.2] found in cache
[uri.1.9.7] found in cache
[uutf.1.0.2] found in cache
[seq.0.2.2] downloaded from cache at https://opam.ocaml.org/cache
[ssl.0.5.5] downloaded from cache at https://opam.ocaml.org/cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
∗ installed base-num.base
∗ installed conf-m4.1
∗ installed conf-pkg-config.1.1
∗ installed conf-which.1
∗ installed num.0
∗ installed conf-libssl.1
∗ installed cmdliner.1.0.4
∗ installed ocamlfind.1.8.1
∗ installed base-bytes.base
∗ installed ppx_tools.5.0+4.05.0
∗ installed ocamlbuild.0.14.0
∗ installed pprint.20180528
∗ installed ssl.0.5.5
∗ installed uchar.0.0.2
∗ installed topkg.1.0.1
∗ installed uutf.1.0.2
∗ installed astring.0.8.3
∗ installed jsonm.1.0.1
∗ installed omd.1.3.1
∗ installed dune.1.6.3
∗ installed base64.2.3.0
∗ installed bigarray-compat.1.0.0
∗ installed jbuilder.transition
∗ installed magic-mime.1.1.2
∗ installed ocp-build.1.99.20-beta
∗ installed cppo.1.6.6
∗ installed cstruct.5.1.1
∗ installed ocaml-compiler-libs.v0.9.0
∗ installed ocp-ocamlres.0.4
∗ installed asak.0.2
∗ installed eqaf.0.5
∗ installed hex.1.4.0
∗ installed ppx_derivers.1.2.1
∗ installed ppx_traverse_builtins.v0.9.0
∗ installed result.1.4
∗ installed seq.0.2.2
∗ installed sexplib.v0.9.3
∗ installed ocp-indent-nlfork.1.5.3
∗ installed stdlib-shims.0.1.0
∗ installed re.1.9.0
∗ installed stringext.1.6.0
∗ installed ocaml-migrate-parsetree.1.3.1
∗ installed base.v0.9.4
∗ installed ezjsonm.1.1.0
∗ installed fmt.0.8.8
∗ installed digestif.0.7.1
∗ installed ppx_ast.v0.9.1
∗ installed ppx_tools_versioned.5.2.2
∗ installed stdio.v0.9.1
∗ installed ppx_core.v0.9.3
∗ installed lwt.3.3.0
∗ installed ppx_optcomp.v0.9.0
∗ installed lwt_ssl.1.1.3
∗ installed logs.0.7.0
∗ installed ppx_driver.v0.9.2
∗ installed fieldslib.v0.9.0
∗ installed ppx_metaquot.v0.9.0
∗ installed ppx_type_conv.v0.9.1
∗ installed ppx_fields_conv.v0.9.0
∗ installed ppx_sexp_conv.v0.9.0
∗ installed ipaddr.2.9.0
∗ installed uri.1.9.7
∗ installed conduit.1.3.0
∗ installed ocplib-json-typed.0.6
∗ installed cohttp.1.1.1
∗ installed conduit-lwt.1.3.0
∗ installed cohttp-lwt.1.1.1
∗ installed conduit-lwt-unix.1.3.0
∗ installed cohttp-lwt-unix.2.1.3
[ERROR] The compilation of learn-ocaml-client failed at "$HOME/.opam/opam-init/hooks/sandbox.sh
        build dune build @install -p learn-ocaml-client".

#=== ERROR while compiling learn-ocaml-client.0.11 ============================#
# context     2.0.5 | linux/x86_64 | ocaml-base-compiler.4.05.0 | pinned(file://$HOME/forge/git/learn-ocaml)
# path        ~/forge/git/learn-ocaml/_opam/.opam-switch/build/learn-ocaml-client.0.11
# command     ~/.opam/opam-init/hooks/sandbox.sh build dune build @install -p learn-ocaml-client
# exit-code   1
# env-file    ~/.opam/log/learn-ocaml-client-10754-d56151.env
# output-file ~/.opam/log/learn-ocaml-client-10754-d56151.out
### output ###
# File "static/dune", line 1, characters 0-38919:
# [...]
#   2 |  (section share)
#   3 |  (files
# .....
# 366 |   (js/mathjax/latest.js as www/js/mathjax/latest.js)
# 367 |  )
# 368 | )
# Error: I can't determine automatically which package this stanza is for.
# I have the choice between these ones:
# - learn-ocaml        (because of learn-ocaml.opam)
# - learn-ocaml-client (because of learn-ocaml-client.opam)
# You need to add a (package ...) field to this (install) stanza.



<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build learn-ocaml-client 0.11
└─ 
┌─ The following changes have been performed
│ ∗ install asak                    0.2
│ ∗ install astring                 0.8.3
│ ∗ install base                    v0.9.4
│ ∗ install base-bytes              base
│ ∗ install base-num                base
│ ∗ install base64                  2.3.0
│ ∗ install bigarray-compat         1.0.0
│ ∗ install cmdliner                1.0.4
│ ∗ install cohttp                  1.1.1
│ ∗ install cohttp-lwt              1.1.1
│ ∗ install cohttp-lwt-unix         2.1.3
│ ∗ install conduit                 1.3.0
│ ∗ install conduit-lwt             1.3.0
│ ∗ install conduit-lwt-unix        1.3.0
│ ∗ install conf-libssl             1
│ ∗ install conf-m4                 1
│ ∗ install conf-pkg-config         1.1
│ ∗ install conf-which              1
│ ∗ install cppo                    1.6.6
│ ∗ install cstruct                 5.1.1
│ ∗ install digestif                0.7.1
│ ∗ install dune                    1.6.3
│ ∗ install eqaf                    0.5
│ ∗ install ezjsonm                 1.1.0
│ ∗ install fieldslib               v0.9.0
│ ∗ install fmt                     0.8.8
│ ∗ install hex                     1.4.0
│ ∗ install ipaddr                  2.9.0
│ ∗ install jbuilder                transition
│ ∗ install jsonm                   1.0.1
│ ∗ install logs                    0.7.0
│ ∗ install lwt                     3.3.0
│ ∗ install lwt_ssl                 1.1.3
│ ∗ install magic-mime              1.1.2
│ ∗ install num                     0
│ ∗ install ocaml-compiler-libs     v0.9.0
│ ∗ install ocaml-migrate-parsetree 1.3.1
│ ∗ install ocamlbuild              0.14.0
│ ∗ install ocamlfind               1.8.1
│ ∗ install ocp-build               1.99.20-beta
│ ∗ install ocp-indent-nlfork       1.5.3
│ ∗ install ocp-ocamlres            0.4
│ ∗ install ocplib-json-typed       0.6
│ ∗ install omd                     1.3.1
│ ∗ install pprint                  20180528
│ ∗ install ppx_ast                 v0.9.1
│ ∗ install ppx_core                v0.9.3
│ ∗ install ppx_derivers            1.2.1
│ ∗ install ppx_driver              v0.9.2
│ ∗ install ppx_fields_conv         v0.9.0
│ ∗ install ppx_metaquot            v0.9.0
│ ∗ install ppx_optcomp             v0.9.0
│ ∗ install ppx_sexp_conv           v0.9.0
│ ∗ install ppx_tools               5.0+4.05.0
│ ∗ install ppx_tools_versioned     5.2.2
│ ∗ install ppx_traverse_builtins   v0.9.0
│ ∗ install ppx_type_conv           v0.9.1
│ ∗ install re                      1.9.0
│ ∗ install result                  1.4
│ ∗ install seq                     0.2.2
│ ∗ install sexplib                 v0.9.3
│ ∗ install ssl                     0.5.5
│ ∗ install stdio                   v0.9.1
│ ∗ install stdlib-shims            0.1.0
│ ∗ install stringext               1.6.0
│ ∗ install topkg                   1.0.1
│ ∗ install uchar                   0.0.2
│ ∗ install uri                     1.9.7
│ ∗ install uutf                    1.0.2
└─ 

<><> jbuilder.transition installed successfully <><><><><><><><><><><><><><><><>
=> Jbuilder has been renamed and the jbuilder package is now a transition package. Use the dune package
   instead.

The former state can be restored with:
    opam switch import
"$HOME/forge/git/learn-ocaml/_opam/.opam-switch/backup/state-20200129163810.export"
```

</details>

Actually learn-ocaml-client doesn't require files in `static`, but in a situation such as my above example of a dirty repository which had compiled learn-ocaml before this PR, this might be an issue.

Do you think one should add `[make "static"]` to this aim in `learn-ocaml-client.opam`?

2. when triggering the installation of learn-ocaml subsequently (without `--locked`), two packages were downgraded:

<details>

```
$ opam pin add -n -y -k path learn-ocaml .
[learn-ocaml.0.10] synchronised from file://$HOME/forge/git/learn-ocaml
learn-ocaml is now pinned to file://$HOME/forge/git/learn-ocaml (version 0.11)

$ opam install learn-ocaml

<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[learn-ocaml.0.11] no changes from file://$HOME/forge/git/learn-ocaml

The following actions will be performed:
  ↘ downgrade cstruct              5.1.1 to 5.0.0 [required by ppx_cstruct]
  ∗ install   conf-git             1.0            [required by learn-ocaml]
  ∗ install   tyxml                4.3.0          [required by js_of_ocaml-tyxml, odoc]
  ∗ install   fpath                0.7.2          [required by odoc]
  ∗ install   rresult              0.6.0          [required by checkseum, bos]
  ∗ install   markup               0.8.2          [required by learn-ocaml]
  ∗ install   easy-format          1.3.1          [required by learn-ocaml]
  ∗ install   optint               0.0.2          [required by decompress]
  ∗ install   react                1.2.1          [required by lwt_react]
  ↘ downgrade ipaddr               2.9.0 to 2.8.0 [required by learn-ocaml]
  ∗ install   ppx_cstruct          5.0.0          [required by learn-ocaml]
  ↻ recompile hex                  1.4.0          [uses cstruct]
  ↻ recompile eqaf                 0.5            [uses cstruct]
  ∗ install   biniou               1.2.0          [required by yojson]
  ∗ install   checkseum            0.0.3          [required by decompress]
  ∗ install   reactiveData         0.2.1          [required by js_of_ocaml-tyxml]
  ∗ install   lwt_react            1.1.3          [required by learn-ocaml]
  ↻ recompile ezjsonm              1.1.0          [uses hex]
  ↻ recompile digestif             0.7.1          [uses eqaf]
  ∗ install   yojson               1.7.0          [required by learn-ocaml]
  ∗ install   decompress           0.8.1          [required by learn-ocaml]
  ∗ install   js_of_ocaml-compiler 3.3.0          [required by learn-ocaml]
  ∗ install   js_of_ocaml          3.3.0          [required by learn-ocaml]
  ∗ install   js_of_ocaml-ppx      3.3.0          [required by learn-ocaml]
  ↻ recompile ocplib-json-typed    0.6            [uses js_of_ocaml]
  ↻ recompile logs                 0.7.0          [uses js_of_ocaml]
  ∗ install   js_of_ocaml-tyxml    3.4.0          [required by learn-ocaml]
  ∗ install   js_of_ocaml-toplevel 3.3.0          [required by learn-ocaml]
  ∗ install   js_of_ocaml-lwt      3.4.0          [required by learn-ocaml]
  ∗ install   bos                  0.2.0          [required by odoc]
  ↻ recompile conduit              1.3.0          [uses ipaddr]
  ∗ install   odoc                 1.3.0          [required by learn-ocaml]
  ↻ recompile conduit-lwt          1.3.0          [uses conduit]
  ↻ recompile conduit-lwt-unix     1.3.0          [uses ipaddr]
  ↻ recompile cohttp-lwt-unix      2.1.3          [uses logs]
  ∗ install   learn-ocaml          0.11*
  ↻ recompile learn-ocaml-client   0.11*          [uses ocplib-json-typed]
===== ∗ 24   ↻ 11   ↘ 2 =====
Do you want to continue? [Y/n] y
```
</details>

An easy way to fix the `ipaddr` issue could be to add the same dependency in learn-ocaml-client as in learn-ocaml? `"ipaddr" {= "2.8.0" }`

Regarding the other downgrade, `cstruct < 5.1.1` seems to be required because `cstruct.5.1.1` requires `js_of_ocaml >= 3.5.0` while it is pinned to `3.3.0`:

```
$ opam show cstruct.5.1.1
[…]
conflicts:    "js_of_ocaml" {< "3.5.0"}
```

so either you could add a dependency constraint `"cstruct" {= "5.0.0"}` in learn-ocaml-client.opam (?) or if you prefer, just postpone this minor issue to the time the `js_of_ocaml` will be bumped to `3.5.x`.

anyway, the above `opam install learn-ocaml` (without `--locked`) was very OK :+1:

3. finally we may want to add some **documentation on how to build only `learn-ocaml-client`**? and **add a dedicated test in the CI** (e.g. by rephrasing the `compilation` stage of the `Dockerfile`)? to ensure that if we only install first the dependencies specified in the learn-ocaml-client.opam, learn-ocaml-client can be built, and learn-ocaml just afterwards. What do you think?

Anyway, I guess these last two things (doc and CI) could be done in another PR :) so feel free to merge #342 after you have taken a quick look at the items 1. and 2. above.

**Comment by erikmd** [comment]
Hi @yurug, another suggestion in passing:

if I'm not mistaken the `learn-ocaml-client` binary does not have ocaml runtime dependencies; so maybe most of the dependencies in the `learn-ocaml-client.opam` file of this PR could be tagged as [build dependencies](https://opam.ocaml.org/doc/Packaging.html#Advanced-usage)?

**Comment by erikmd** [comment]
BTW to follow-up https://github.com/ocaml-sf/learn-ocaml/pull/342#issuecomment-579871426 :

> 3. finally we may want to add some **documentation on how to build only `learn-ocaml-client`**?

for the record, one can use the following commands to build it using opam:

```
opam switch create . ocaml-base-compiler.4.05.0 --no-install  # to adapt/remove if need be
eval $(opam env)
opam pin add -n -y -k path learn-ocaml-client .
opam install learn-ocaml-client
```

> and **add a dedicated test in the CI** (e.g. by rephrasing the `compilation` stage of the `Dockerfile`)? to ensure that if we only install first the dependencies specified in the learn-ocaml-client.opam, learn-ocaml-client can be built, and learn-ocaml just afterwards.

On second thought, maybe it'd be good as well not to "refactor" the current Dockerfile which works well, but add another `Dockerfile.test-client` (and/or another Travis-CI job) that would run the above commands?

**Comment by yurug** [comment]
Erik, thank you for your review. I will not have the time today to tackle your proposal to add a new CI job for learn-ocaml-client. That is, of course, a good idea though.

**Pull request merged**
