### PR TITLE
Make find_binding match annotated declarations

### PR DESCRIPTION
**Pull request by hferee**
Fixes ocaml-sf/learn-ocaml#424

### CODE REVIEW

**Review by erikmd — APPROVED** [review]
Thanks @hferee for opening #424 then proposing a patch!

Could you rename your PR title so that it is more descriptive? (it's enough if the `Fixes #424` string is only in the commit message or PR description; while the PR title will appear in the Merge commit and should be self-contained)

@yurug do you know whether it'd be necessary to add a small test here: https://github.com/ocaml-sf/learn-ocaml/tree/master/tests ?

At first sight, I'd say no… (as no risk of regression is expected 😅)

**Comment by yurug** [comment]
> @yurug do you know whether it'd be necessary to add a small test here: https://github.com/ocaml-sf/learn-ocaml/tree/master/tests ? 
> At first sight, I'd say no… (as no risk of regression is expected )

That would not hurt: @hferee, would you mind doing it, please?

**Comment by hferee** [comment]
> That would not hurt: @hferee, would you mind doing it, please?

Here you go! Please let me know if more tests are necessary.

**Comment by yurug** [comment]
Thanks!

**Comment by erikmd** [comment]
Thanks @hferee! LGTM as well. So let's merge your PR after setting its milestone to 0.13.

**Comment by hferee** [comment]
> BTW @hferee, you may want to checkout the page https://github.com/settings/emails to see if your e-mail `feree(AT)irif(DOT)fr` could be added there.
> 
> Otherwise, GitHub is currently unable to associate your commits and your user account: 2021-09-28_19-56-30_Screenshot_Hugo_commit_email
> 
> But if you fix this, you'll see your name appear in https://github.com/ocaml-sf/learn-ocaml/graphs/contributors

Well, sure. Not that I'm doing this for fame :smile:

**Comment by yurug** [comment]
> Well, sure. Not that I'm doing this for fame smile

The honor is on our side!

**Pull request merged**
