### PR TITLE
Fix dune constraints, Relax most learn-ocaml deps & Add another CI job

### PR DESCRIPTION
**Pull request by erikmd**
see also https://github.com/ocaml/opam-repository/pull/15877 for details

### CODE REVIEW

**Comment by erikmd** [comment]
Cc @yurug hopefully the CI will be green here as well :)

**Comment by erikmd** [comment]
@yurug the macOS job failed, but the failure looks like a network issue or so:

```
[uutf.1.0.1] downloaded from cache at https://opam.ocaml.org/cache
[ERROR] The sources of the following couldn't be obtained, aborting:
          - lwt.3.3.0: Download command failed
          - lwt_react.1.1.1: Download command failed
          - lwt_ssl.1.1.2: Download command failed
          - magic-mime.1.1.1: Download command failed
          - markup.0.8.0: Download command failed
          - ocaml-compiler-libs.v0.9.0: Download command failed
          - ocaml-migrate-parsetree.1.3.1: Download command failed
          - ocamlbuild.0.14.0: Download command failed
          - ocamlfind.1.8.0: Download command failed
          - ocp-build.1.99.20-beta: Download command failed
          - ocp-indent-nlfork.1.5.3: Download command failed
```

Maybe you could restart the build in Travis?

**Comment by erikmd** [comment]
Dear @yurug, I think this PR is ready. To sum up:
* it incorporates the suggestions raised by opam maintainers when integrating `learn-ocaml.0.12`, in particular, `dune` should not be tagged as `build` dependency, and the related command should be <code>"dune" "build" "@install" "-p" name <b>"-j" jobs</b></code>)
* it implements an earlier suggestion https://github.com/ocaml-sf/learn-ocaml/pull/342#issuecomment-583733498, adding a Travis CI job to specifically test the "installability" of `learn-ocaml-client` alone from a fresh switch.

The CI is green now! could you have a final look?

**Comment by yurug** [comment]
Thanks!

**Pull request merged**
