### PR TITLE
Placement toplevel buttons

### PR DESCRIPTION
**Pull request by beobillly**
issue #202

I propose this solution.
It works on different size and with mobile format. Buttons are placed on top of the toplevel pane so they are always visible.

the toplevel input has been moved at the bottom of the window

toplevelplacement

toplevelplacement2

### CODE REVIEW

**Comment by yurug** [comment]
There is a risk that the buttons hide the text, right?

**Comment by beobillly** [comment]
It's automatically resized depending on the size of the screen.
The buttons can't hide the text. At worst they are just above it.
If you found it's too close I can arrange that.

Also I just found out that I did that for the toplevel of the Exercise menu but not for the toplevel of Activities menu, would you like me to do the same for it ?

toplevel of Activities
toplevel of activities

toplevel of Exercises
toplevel of exercise

**Comment by beobillly** [comment]
I changed the placement of the Activities toplevel buttons at the same place than the Exercices.

**Comment by yurug** [comment]
Thanks!

**Pull request merged**
