### PR TITLE
Add entry point for exercise information

### PR DESCRIPTION
**Pull request by leunam217**
imagen

### CODE REVIEW

**Comment by leunam217** [comment]
Don't merge this pull request i find some display error. When the exercise has a title and a description the aesthetics are horrible.

**Comment by yurug** [comment]
What is the status of this PR? @leunam217

**Comment by erikmd** [comment]
Hi @yurug AFAICT, this PR is almost-ready, but the layout should probably be made more responsive (so that for example, if the browser window is resized to fit the half of the screen, the metadata will be hidden and available in a tab…)

**Comment by erikmd** [comment]
> the layout should probably be made more responsive (so that for example, if the browser window is resized to fit the half of the screen, the metadata will be hidden and available in a tab…)

I plan to address this soon / this week.

**Comment by yurug** [comment]
What is the status of this PR? @erikmd

**Comment by erikmd** [comment]
Hi @yurug, sorry for the delay… this PR is still work-in-progress.
But I can try to finalize it this WE (otherwise feel free to ping me then!)

**Comment by erikmd** [comment]
I've just fix the conflict, extended and polished this PR,
but as I don't have access to @leunam217's source repo, I'll open a new PR.

@yurug please close this PR #297, I don't have the rights to do so.

**Pull request closed without merging**
