### PR TITLE
Fix & Document static deployment CLI support

### PR DESCRIPTION
**Pull request by erikmd**
* Kind: **fix**
* Follow-up of #356 
* This PR is mostly a cherry-pick/rework of four commits of the not-yet-ready PR for LTI/Moodle:
  * cf4241cfd54fb776ce891f9afa213cf90dcd27a4
  * ca0bd135da3d0793b407ea99f504ed159a415bcf
  * d75a57af2a50b85c27fe16ba104593a238902050
  * dfe64ae15e015b524cdeb503efd1e37c7de06268
* Basically, it renames `--root` to the more standard name `--base-url` and accepts a `LEARNOCAML_BASE_URL` environment variable.

### CODE REVIEW

**Comment by erikmd** [comment]
@yurug I made several tests, see e.g. https://pfitaxel.github.io/pfitaxel-demo-dev/ for an example of static deployment of this PR (commit 90f391b) on the default demo-repository. and I believe the PR is ready (except the extension of the documentation itself, that may be done in this PR or in another PR?)

**Comment by yurug** [comment]
@erikmd If you can extend the documentation in this PR, we would be sure that it will not be forgotten...

**Comment by erikmd** [comment]
Hi @yurug 
> If you can extend the documentation in this PR, we would be sure that it will not be forgotten...

Done! here is the [direct link](https://github.com/ocaml-sf/learn-ocaml/blob/73f56f0b0715139d990be2f32614cca46066901e/docs/howto-deploy-learn-ocaml-statically.md) so you can proofread :)

(btw, sorry for the multiple force-pushes :)

**Comment by erikmd** [comment]
> (btw, sorry for the multiple force-pushes :)

and if you see my message on-time, feel free to stop all current runs (except the last one):
https://github.com/ocaml-sf/learn-ocaml/actions

**Comment by yurug** [comment]
Thank you @erikmd! That's a really nice work.

**Pull request merged**
