### PR TITLE
Playground activity

### LINKED ISSUE #277: Simplified exercise mode for lecture use
We would very much appreciate having a stripped-down version of the exercise mode to use for demonstrations in lecture. This mode would have the editor on the left and the toplevel on the right: no grader and no Exercise/Report/Details tabs. Each "exercise" would consist of just a template code file to be preloaded into the editor, and possibly a metadata file with a title and short description.

Currently to do demonstrations using Learn-OCaml in class we have a dummy exercise where we have to copy and paste the code we want to cover in class into the editor. After class we copy and paste the code written in class to a new file to upload to the course website. To play with the code students need to download the file and copy and paste its contents into the editor in the dummy exercise, and overwrite whatever code they had in there previously. Having the lecture code pre-loaded into Learn-OCaml in a separate "exercise" for each lecture would simplify this process.

### PR DESCRIPTION
**Pull request by nobrakal**
Hi,

This (big) PR fixes #277.

Mainly, it adds a playground activity, with, as requested, only the editor and a top-level. A playground is only specified by a `template.ml` file (and maybe a `prelude.ml`, made in prevision of #254 ), and one can attach a tittle and a short description if desired, to be displayed in the selection panel.

A `playground` repository is made after an `exercises` one, and has a structure like:

```
playground
├── index.json
├── monad_list
│   ├── prelude.ml
│   └── template.ml
└── monad_option
    └── template.ml
```

and is rendered as:

Screenshot_2019-06-24 Learn OCaml v 0 11(3)

Screenshot_2019-06-24 monad_option - Learn OCaml v 0 11

Note that actually, user code is never sent to the server (there is no "sync" button), and no token is ever required.

Since all of this is based on how exercises are processed, I tried to factorize code where I was able to.

I added an example in `demo-repository`, but I don't know where to document the change...

### CODE REVIEW

**Comment by nobrakal** [comment]
Travis is failing because of a malloc error of opam on macosx:
```
opam(95527,0x7fff920c6340) malloc: *** mach_vm_map(size=259407338536550400) failed (error code=3)
```

The test suite passed on linux.

**Comment by adhameer** [comment]
Thanks for working on this! This is pretty much exactly what we were looking for.

Could the Compile (typecheck) button be added back above the editor?

**Comment by nobrakal** [comment]
Great!

> Could the Compile (typecheck) button be added back above the editor?

Of course, I have added it:

Screenshot_2019-06-25 monad_option - Learn OCaml v 0 11

**Comment by yurug** [comment]
@nobrakal I let you fix the conflict.

**Comment by nobrakal** [comment]
@yurug  Done.

As advertised, if there is a prelude, it will be shown:

Screenshot_2019-06-25 monad_option - Learn OCaml v 0 11

**Comment by adhameer** [comment]
Thanks, this looks great!

**Comment by yurug** [comment]
@nobrakal There is still a conflict to solve.

**Pull request merged**
