### PR TITLE
Allows some basic configuration of the welcome screen messages

### PR DESCRIPTION
**Pull request by AltGr**

### CODE REVIEW

**Comment by yurug** [comment]
I do not understand how the user interface to this configuration system. Can you explain how this works please?

**Comment by AltGr** [comment]
there is not much at the moment, that part needs improvement: one would need to first run `learn-ocaml build`, then edit the `www/js/learnocaml-config.js` by hand.

The idea is that options should be added to `learn-ocaml build` to allow specifying this kind of things. Note that this is already how the `enable|disable` flags for the different tabs are handled (with appropriate options, in the this case)

**Comment by yurug** [comment]
Thanks for the explanations. 

Does `learn-ocaml build` replace the configuration file each time it is run?

Should we document this?

**Comment by AltGr** [comment]
> Does `learn-ocaml build` replace the configuration file each time it is run?

yes :/

> Should we document this?

if we add options to `learn-ocaml build` — or better (?), a way to supply the config file — the doc can easily be part of the man-page.

**Comment by yurug** [comment]
Could we say that if a file named `learnocaml-config.js` is present in the root of the repository, then it is copied in `www/js` by the `learn-ocaml build` command?

**Comment by AltGr** [comment]
In any case, there should be no downside to merging this now, and improving interface/doc afterwards. Let's just keep #123 open to make sure it doesn't stay unfinished.

**Comment by AltGr** [comment]
> Could we say that if a file named learnocaml-config.js is present in the root of the repository, then it is copied in www/js by the learn-ocaml build command?

One downside of this approach is that, on errors in the file, nothing will be reported at build-time but the resulting app may be broken. I'll define a proper Json format, will take a few minutes and also help with documentation, then export it to the `learnocaml-config.js` file.

**Comment by yurug** [comment]
Good idea!

**Pull request merged**
