### PR TITLE
fix: better error msg for X-token registration

### PR DESCRIPTION
**Pull request by EmileRolley**
This PR fix the first point suggered by @erikmd in the issue #405.

### CODE REVIEW

**Review by erikmd — APPROVED** [review]
Thanks, will merge as soon as the CI terminates.

**Comment by erikmd** [comment]
BTW @EmileRolley regarding GitHub assignees, if you don't disagree I'd suggest we follow the same approach as that of the Coq dev. team… which is a bit standard IINM:

* On an issue, the assignee is the developer/maintainer that will address the issue (open a PR)
* On a PR, the assignee is the maintainer that will merge the PR (after the approval from the reviewer(s))

**Comment by EmileRolley** [comment]
> BTW @EmileRolley regarding GitHub assignees, if you don't disagree I'd suggest we follow the same approach as that of the Coq dev. team… which is a bit standard IINM:
> 
> * On an issue, the assignee is the developer/maintainer that will address the issue (open a PR)
> * On a PR, the assignee is the maintainer that will merge the PR (after the approval from the reviewer(s))

MB, I will update this.

**Comment by erikmd** [comment]
Just a minor comment: it seems GItHub did not recognized your two e-mails as associated to your account:

2021-07-20_15-26-44_Screenshot_GH_logo

maybe because you did `git commit --amend` and not `git commit --amend --reset-author`? cf. this screenshot from `gitk`:

2021-07-20_15-27-40_Screenshot_emails

anyway I guess it's a very minor issue! and it might suffice for you to keep this commit as is, and add the other e-mail address here? https://github.com/settings/emails

**Comment by EmileRolley** [comment]
> maybe because you did `git commit --amend` and not `git commit --amend --reset-author`?

Indeed :sweat_smile:. It's fixed.

**Pull request merged**
